version: '3.4'

services:

  mysql:
    image: mysql:latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  daprtest.orderapi:
    image: ${DOCKER_REGISTRY-}daprtestorderapi
    build:
      context: .
      dockerfile: DaprTest.OrderApi/Dockerfile
    
  daprtest.orderapi.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprtest.orderapi
    network_mode: "service:daprtest.orderapi"

  daprtest.productapi:
    image: ${DOCKER_REGISTRY-}daprtestproductapi
    build:
      context: .
      dockerfile: DaprTest.ProductApi/Dockerfile

  daprtest.productapi.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprtest.productapi
    network_mode: "service:daprtest.productapi"


  daprtest.memberapi:
    image: ${DOCKER_REGISTRY-}daprtestmemberapi
    build:
      context: .
      dockerfile: DaprTest.MemberApi/Dockerfile

  daprtest.memberapi.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprtest.memberapi
    network_mode: "service:daprtest.memberapi"


  daprtest.identityserver:
    image: ${DOCKER_REGISTRY-}daprtestidentityserver
    build:
      context: .
      dockerfile: DaprTest.IdentityServer/Dockerfile

  daprtest.ui.mvc:
    image: ${DOCKER_REGISTRY-}daprtestuimvc
    build:
      context: .
      dockerfile: DaprTest.UI.MVC/Dockerfile

  daprtest.ui.js:
    image: ${DOCKER_REGISTRY-}uijs
    build:
      context: .
      dockerfile: DaprTest.UI.JS/wwwroot/Dockerfile




