version: '3.4'

services:
  mysql:
    container_name: mysqldapr
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - D://docker/mysqldapr/db:/var/lib/mysql
      - D://docker/mysqldapr/config:/etc/my.cnf
    ports:
      - "3307:3306"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "5379:6379"

  zipkin:
    ports:
      - "5411:9411"

  daprtest.payapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=pay_db;user ID=root;Password=123456;
      - IdentityServerUrl=http://${LOCALHOST_IP}:7000
  daprtest.payapi.dapr:
    command: [ "./daprd",
    "-app-id", "payapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  daprtest.storeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=store_db;user ID=root;Password=123456;
      - IdentityServerUrl=http://${LOCALHOST_IP}:7000
  daprtest.storeapi.dapr:
    command: [ "./daprd",
    "-app-id", "storeapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  daprtest.tenantapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=tenant_db;user ID=root;Password=123456;
      - IdentityServerUrl=http://${LOCALHOST_IP}:7000
  daprtest.tenantapi.dapr:
    command: [ "./daprd",
    "-app-id", "tenantapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  daprtest.orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=order_db;user ID=root;Password=123456;
      - IdentityServerUrl=http://${LOCALHOST_IP}:7000


  daprtest.orderapi.dapr:
    command: [ "./daprd",
    "-app-id", "orderapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  daprtest.productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=product_db;user ID=root;Password=123456;
      - IdentityServerUrl=http://${LOCALHOST_IP}:7000


  daprtest.productapi.dapr:
    command: [ "./daprd",
    "-app-id", "productapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  daprtest.memberapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=member_db;user ID=root;Password=123456;
      - IdentityServerUrl=http://${LOCALHOST_IP}:7000


  daprtest.memberapi.dapr:
    command: [ "./daprd",
    "-app-id", "memberapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"


  daprtest.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=member_db;user ID=root;Password=123456;
      - MVCUrl=http://${LOCALHOST_IP}:7001
      - JSUrl=http://${LOCALHOST_IP}:7002
    ports:
      - "7000:80"

  daprtest.ui.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #内部访问又要浏览器跳转，用服务名能内部访问不能跳转，用localhost能跳转，不能内部访问，所以用IP
      - IdentityServerUrl=http://${LOCALHOST_IP}:7000  
      # 服务间的内部http访问可以使用服务名,内部访问更推荐用dapr访问
      - ApiUrl=http://daprtest.nginxgateway
    ports:
      - "7001:80"

  daprtest.ui.js:
    ports:
      - "7002:80"

  daprtest.nginxgateway:
    ports:
      - "6001:80"



