version: '3.4'

services:

  mysql:
    image: mysql:latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  daprtest.payapi:
    image: ${DOCKER_REGISTRY-}daprtestpayapi
    build:
      context: .
      dockerfile: DaprTest.PayApi/Dockerfile
  daprtest.payapi.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprtest.payapi
    network_mode: "service:daprtest.payapi"

  daprtest.tenantapi:
    image: ${DOCKER_REGISTRY-}daprtesttenantapi
    build:
      context: .
      dockerfile: DaprTest.TenantApi/Dockerfile
  daprtest.tenantapi.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprtest.tenantapi
    network_mode: "service:daprtest.tenantapi"

  daprtest.orderapi:
    image: ${DOCKER_REGISTRY-}daprtestorderapi
    build:
      context: .
      dockerfile: DaprTest.OrderApi/Dockerfile   
  daprtest.orderapi.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprtest.orderapi
    network_mode: "service:daprtest.orderapi"

  daprtest.productapi:
    image: ${DOCKER_REGISTRY-}daprtestproductapi
    build:
      context: .
      dockerfile: DaprTest.ProductApi/Dockerfile
  daprtest.productapi.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprtest.productapi
    network_mode: "service:daprtest.productapi"


  daprtest.memberapi:
    image: ${DOCKER_REGISTRY-}daprtestmemberapi
    build:
      context: .
      dockerfile: DaprTest.MemberApi/Dockerfile
  daprtest.memberapi.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - daprtest.memberapi
    network_mode: "service:daprtest.memberapi"

  daprtest.nginxgateway:
    image: daprtest.nginxgateway
    build:
      context: .
      dockerfile: gateway/nginxgateway/Dockerfile

  daprtest.identityserver:
    image: ${DOCKER_REGISTRY-}daprtestidentityserver
    build:
      context: .
      dockerfile: DaprTest.IdentityServer/Dockerfile

  daprtest.ui.admin:
    image: ${DOCKER_REGISTRY-}daprtestuiadmin
    build:
      context: .
      dockerfile: DaprTest.UI.Admin/Dockerfile

  daprtest.ui.tenant:
    image: daprtest.ui.tenant
    build:
      context: .
      dockerfile: DaprTest.UI.Tenant/ClientVue/dist/Dockerfile

  daprtest.ui.defaulttenantweb:
    image: daprtest.ui.defaulttenantweb
    build:
      context: .
      dockerfile: DaprTest.UI.DefaultTenantWeb/wwwroot/Dockerfile






